Atlas-Authority/marketing-automation

package-lock.json
package.json
src/bin/check-licenses.ts
src/lib/engine/deal-generator/actions.ts
src/lib/engine/deal-generator/events.ts
src/lib/engine/deal-generator/generate-deals.ts
src/lib/engine/deal-generator/ignore-apps.ts
src/lib/engine/engine.ts
src/lib/engine/summary.ts
src/lib/log/table.ts
src/lib/log/tallier.ts
src/lib/model/contact.ts
src/lib/model/database.ts
src/lib/model/deal.ts
src/lib/model/license.ts
src/lib/model/transaction.ts
src/lib/util/formatters.ts
src/lib/util/helpers.ts

Fix issue with sometimes double-updating deals

---

src/lib/engine/deal-generator/actions.ts
src/lib/engine/deal-generator/generate-deals.ts

Every event has an action generated for it. But previously, all actions that result in no upsync-able changes to an existing deal, were ignored. Now, we include those in the associate-deals-to-contacts-and-companies code. The first commit in this PR is the one that makes that change, and nothing else. The second commit just cleans up the code.
Resolves #51.

Backfill associations

---

.sample.env
src/lib/io/live/hubspot.ts
src/lib/parameters/env.ts

1. When creating the app, the engine need read/write scopes for contact/deal/company (6 total).
2. There's a new key `HUBSPOT_ACCESS_TOKEN` for this, but using an API key will still work too.
3. Either `HUBSPOT_ACCESS_TOKEN` or `HUBSPOT_API_KEY` must be provided.

Optionally allow access token from HubSpot private app.

---

docs/ENGINE.md
src/lib/cache/datadir.ts
src/lib/engine/deal-generator/actions.ts
src/lib/engine/deal-generator/events.ts
src/lib/engine/deal-generator/generate-deals.ts
src/lib/engine/deal-generator/records.ts

This saves deal generator records, events, and actions to a file. This has three benefits:
1. It's useful for examining engine logic, to either understand it, verify it, or change it
2. It's useful for figuring out what actually happened to a deal and why
3. It's useful as a first step to sample test data (see #23); the main thing left is redacting IDs
It also was the wrong way to use the "detailed" log level, which is now unused and waiting for legitimate usage.

Save intermediate deal generation data

---

docs/ENGINE.md
src/lib/engine/deal-generator/actions.ts

This code was possibly updating deals to closed-won when they were closed-lost. It was always closed-won before, assuming it was either an eval or a closed-won, figuring it would make no difference. But if it was refunded, it would change it from closed-lost to closed-won. This code tries to fix that, and possibly does.

Don't set refunded deals to closed-won.

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

1. Makes it much easier for other devs to clone this repo into a fully-ready dev environment
2. Makes sure the project's Node version doesn't clash with any dev's local node version
3. Allows devs to avoid even having Node set up locally, they just need VS Code
4. Installs a few project-specific VS Code extensions for you (questionably used here)
5. If you don't use Docker or VS Code, these config files have no negative impact, and the project still works
This could be a useful pattern for more projects. @khanguyen88 what do you think?

Add dev-container for consistent dev experience.

---

package-lock.json
package.json
src/lib/engine/deal-generator/actions.ts
src/lib/engine/deal-generator/events.ts
src/lib/engine/deal-generator/generate-deals.ts
src/lib/engine/deal-generator/logger.ts
src/lib/engine/deal-generator/records.ts

1. Prints generated deal-actions in nicer format for manual inspection (instead of just JSON)
2. Redacts all IDs, amounts, and identifying info from generated output
This should help create realistic test cases for #23 using real data but with redacted information.

Redact sensitive information from deal generation data output

---

src/lib/engine/deal-generator/events.ts
src/lib/engine/deal-generator/logger.ts
src/lib/model/transaction.ts

This finishes most of the subtask in #23 of generating sample data with a redacted copy.
1. The redacted IDs match the format of real IDs, so we'll end up with fake addon-license-ids like L64504661 and 89032315, fake transaction-ids like AT-646765546, and fake deal-ids like 5679651591.
2. The redacted combined-transaction-and-addon-license-ids are now redacted in parts, so they're not "unrelated" to existing IDs. So for example, for AT-646765546 and 89032315, we now print AT-646765546[89032315] whereas before this PR it was a random string that had nothing to do with either of those.
3. We now also print the Transaction/License IDs, deal stage, and amount, for deals that have no action taken on them. This will be useful for quickly seeing (and verifying) why the engine thought no action …

Generate test data

---

docs/ENGINE.md
src/bin/generate-test.ts
src/lib/engine/contacts/update-contacts.ts
src/lib/engine/deal-generator/actions.ts
src/lib/engine/deal-generator/events.ts
src/lib/engine/deal-generator/generate-deals.ts
src/lib/engine/deal-generator/logger.ts
src/lib/engine/deal-generator/records.ts
src/lib/engine/deal-generator/test/utils.ts
src/lib/engine/license-matching/license-grouper.ts
src/lib/model/license.ts
src/lib/model/transaction.ts

The recent test suite PR had one regression, due to passing a list of MPAC records *after* combining evals. This meant it couldn't find a license for a given `addonLicenseId`.
But the good news is that this made me realize that *there's absolutely no need for a LicenseContext type.* We can just use a License, which can have an array of its Transactions, and each Transaction can store a ref to its License.
This will also help in the Partner Transactions task, which has to traverse licenses and transactions in order to find out their contacts and contact types. From now on, we should always be linking refs as early on as we can in the engine.

Fix run regression

---

src/bin/cli-args.ts
src/bin/download.ts
src/bin/main.ts
src/lib/engine/contacts/generate-contacts.ts
src/lib/engine/contacts/update-contacts.ts
src/lib/engine/deal-generator/actions.ts
src/lib/engine/deal-generator/events.ts
src/lib/engine/deal-generator/generate-deals.ts
src/lib/engine/deal-generator/logger.ts
src/lib/engine/deal-generator/test/test-cases/basics.test.ts
src/lib/engine/deal-generator/test/test-cases/partner-transacted.test.ts
src/lib/engine/deal-generator/test/utils.ts
src/lib/engine/summary.ts
src/lib/io/io.ts
src/lib/io/live/hubspot.ts
src/lib/io/live/marketplace.ts
src/lib/io/slack.ts
src/lib/model/database.ts
src/lib/model/deal.ts
src/lib/model/marketplace/record.ts
src/lib/parameters/env-config.ts
src/lib/parameters/interfaces.ts
src/lib/util/runner.ts

This fixes #70 by updating the reporting summary.
It also updates the previous engine behavior which wasn't letting partner-only transactions get through to the deal-generator phase, so that deals are created for them now, and marked as closed-won, but with "Associated Partner" set.
Oh I also did a tiny bit of work towards moving ENV stuff out of the engine logic, so that tests can run without having ENV variables set (ie. in GH/CI). There's more work towards that, but I wasn't going to put this PR off for that.
It also corrects the implementation of the associated partners, which was slightly wrong.

Fix balance summary reporting

---

docs/HUBSPOT.md
src/lib/engine/deal-generator/actions.ts
src/lib/engine/deal-generator/redact.ts
src/lib/engine/deal-generator/test/test-cases/smoke.test.ts
src/lib/engine/deal-generator/test/utils.ts
src/lib/model/database.ts
src/lib/model/deal.ts
src/lib/model/license.ts
src/lib/model/transaction.ts
src/lib/parameters/env-config.ts

After this PR is merged, HubSpot deals will be updated to have the 2 new IDs when present, and MAE will try to use these to look up deals before using SEN.
This PR does half of #16. This doesn't finish the SEN-replacement feature, though. The engine assumes addonLicenseId is always present.
So we'll need to do one more PR after this, to replace this assumption in the engine with these new assumptions:
1. AddonLicenseId may sometimes be missing
2. Entitlement{Id,Number} may sometimes be present
3. Ostensibly, after SEN is removed, these will be mutually exclusive, so either 1 or 2 is present, but never both
4. Until SEN is removed, there will be SEN and possibly ENT2. (I'm just gonna call them both ENT2 from now on.)
@bberenberg when you get a second, please let me know if these …

Prepare SEN replacements

---

.vscode/launch.json
README.md
docs/ENGINE.md
package.json
src/bin/generate-test.ts
src/bin/run-3x.ts
src/lib/engine/deal-generator/test/utils.ts
src/lib/engine/license-matching/license-grouper.ts
src/lib/model/database.ts
src/lib/model/deal.ts
src/lib/model/license.ts
src/lib/model/marketplace/common.ts
src/lib/model/marketplace/raw.ts
src/lib/model/marketplace/validation.ts
src/lib/model/transaction.ts
src/lib/util/helpers.ts

A few places needed to be updated that were missed:

Finish SEN replacement

---

.sample.env
README.md
package-lock.json
package.json
src/bin/analyze-data-shift.ts
src/bin/main.ts
src/lib/config/env.ts
src/lib/data-shift/analyze.ts
src/lib/data-shift/loader.ts
src/lib/data-shift/multi-id-map.ts
src/lib/data-shift/reporter.ts
src/lib/data/csv.ts
src/lib/data/file.ts
src/lib/data/manager.ts
src/lib/data/set.ts
src/lib/engine/slack-notifier.ts
src/lib/hubspot/hubspot.ts
src/lib/log/download.ts
src/lib/log/table.ts
src/lib/marketplace/marketplace.ts
src/lib/marketplace/structure.ts
src/lib/marketplace/validation.ts
src/lib/model/license.ts
src/lib/model/transaction.ts
src/tests/multi-id-map.test.ts

This closes subtask #82 and finishes out #59.
When it runs:
- Data shift analyzation runs directly after each loop in Docker
- Local dev can run it manually as an NPM task
How it reports:
- If Slack is configured via ENV, sends message to Slack error channel
- Always prints to standard out and standard error
Configuration it runs with:
- Can set ENV variable for late-transaction threshold
- Defaults to 30 days (ignores transactions that appear 29 days later)
What it does:
- Checks for missing transactions
- Checks for missing licenses
- Checks for transactions that appear later than claimed
- Checks for altered transactions
- Checks for altered licenses
Altered license fields checked:
- `addonKey`
- `addonName`
- `hosting`
- `maintenanceStartDate`
Altered transaction fields checked:
- …

Analyzes data across data sets, and reports to Slack

---

.sample.env
README.md
docs/HUBSPOT.md
package-lock.json
package.json
src/lib/config/env.ts
src/lib/hubspot/entity.ts
src/lib/hubspot/interfaces.ts
src/lib/model/company.ts
src/lib/model/contact.ts
src/lib/model/deal.ts

Closes #64 
---
Given this sample configuration:
```env
HUBSPOT_MANAGED_DEAL_FIELDS=country
HUBSPOT_MANAGED_CONTACT_FIELDS=firstname,lastname
```
Then when we try to create or update a contact:
* If contact's "firstname" was empty before, or contact is being created by MAE
* It will be set/updated according to normal engine logic
* Otherwise if it's non-blank:
* Any updates to this field will be skipped in the engine

Can specify managed HubSpot fields via ENV variables.

---

src/lib/data-shift/analyze.ts
src/lib/data-shift/reporter.ts
src/lib/model/license.ts
src/lib/model/transaction.ts

Fixes #91 
* Transaction IDs not prefixed with AT (e.g. refunds) have `(AT)` prefixed for clarity
* License IDs have ALI, AEI, or AEN prefixed to them
* "Timestamp" column has been renamed to "When Not Found"
* Column "When Last Seen" has been added
* About 30 calories were spent on this PR according to [Harvard Health Publications](https://www.health.harvard.edu/blog/the-truth-behind-standing-desks-2016092310264)
* That number [was probably increased](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5435671/) with assistance from Royal Deluxe
Examples:
```
Deleted Transactions                                                                          
Transaction Unique ID          When Last Seen                  When Not Found               
---------------------          -------------- …
```

Fix data shift reports

---

src/lib/hubspot/manager.ts

This apparently happens because sometimes an entity kind can be "company_unlabeled" instead of just "company". Not sure why. Quick fix here is to just remove "_unlabeled" from it, which gets the engine working again. Longer term, we need to know what this type is and why HubSpot is giving it to us sometimes. Googled it and found nothing.

Fixes entity-linking bug

---

src/lib/marketplace/validation.ts

Resolves #105 by reporting an error when MPAC returns empty data for partner contact details

Fix MPAC input validation for empty partner data

---

.vscode/launch.json
README.md
docs/ENGINE.md
docs/HUBSPOT.md
package-lock.json
package.json
src/lib/contact-generator/contact-generator.ts
src/lib/contact-generator/update-contacts.ts
src/lib/hubspot/entity.ts
src/lib/hubspot/interfaces.ts
src/lib/model/contact.ts
src/tests/generate-contacts.test.ts

Make Contact Deployment field multiselect

---

src/lib/hubspot/entity.ts
src/lib/model/contact.ts

The value is undefined because it's a created entity, and in src/lib/hubspot/manager.ts:71 it gives an empty object as its old-data param. In this case, all fields will be undefined for the old value. Rather than checking each of them, we can just check the value on the line in this PR and use the blank string to mean no-value when comparing with the new value, which must be an empty string for blank values anyway.

Better fix for set comparison bug recently introduced

---

.vscode/settings.json
README.md
src/lib/deal-generator/actions.ts

This is a better fix than #132, because it makes the cause clearer and addresses it more directly, which is that sometimes every deal in a group of duplicates has had manual HubSpot activity, so none of them can be deleted. It will still go through the usual logging of links to these duplicate deals for manual resolution.

Fix deal duplication finding bug

---

src/lib/hubspot/api.ts

Before:
```
Error: Failed downloading companys: undefined
at HubspotAPI.downloadHubspotEntities (C:\projects\marketing-automation\src\lib\hubspot\api.ts:69:15)
at runNextTicks (node:internal/process/task_queues:60:5)
at processTimers (node:internal/timers:504:9)
at MultiDownloadLogger.wrap (C:\projects\marketing-automation\src\lib\log\download.ts:20:20)
at async Promise.all (index 6)
at downloadAllData (C:\projects\marketing-automation\src\lib\engine\download.ts:19:16)
```
After:
```
Error: Failed downloading companys.
Response body: undefined
Error stacktrace: AssertionError [ERR_ASSERTION]: "contractor" does not start with "company_to_" for "1234567890" to "987654321"
at C:\projects\marketing-automation\src\lib\hubspot\api.ts:45:22
at Array.map (<anonymous>)
at …
```

Better error messages for HubSpot Association API errors

---

src/bin/download.ts
src/bin/main.ts
src/lib/config/env.ts
src/lib/contact-generator/contact-generator.ts
src/lib/data-shift/reporter.ts
src/lib/deal-generator/actions.ts
src/lib/engine/download.ts
src/lib/engine/slack-notifier.ts
src/lib/hubspot/api.ts
src/lib/hubspot/entity.ts
src/lib/hubspot/hubspot.ts
src/lib/hubspot/interfaces.ts
src/lib/hubspot/manager.ts
src/lib/hubspot/uploader.ts
src/lib/log/download.ts
src/lib/log/logdir.ts
src/lib/model/contact.ts
src/lib/model/deal.ts
src/lib/model/transaction.ts

For #142 
The previous implementation in #143 did not take into account that `contractor` could be on the `contact` side or the `company` side of such an association. This implementation also moves the logic to a more appropriate spot in the engine.

Fixes HubSpot custom association support.

---

.vscode/launch.json
src/lib/hubspot/manager.ts
src/lib/marketplace/api.ts
src/lib/marketplace/validation.ts

This finishes #142 by updating data-shift-analysis code to support custom HubSpot association types. Previously stored data sets used a different association format than what we now use since #144, and the code wasn't able to support both formats. This PR supports both the old and new association formats in stored data sets, so that data-shift-analysis code will now work again.

Fix HubSpot custom association support

---

src/lib/marketplace/validation.ts
src/lib/model/transaction.ts

If tier is not present, then return `-1` as number of users.

Remove tier validation
